import type { Arquetipo, TipoModulo } from '../types';

/**
 * Hybrid 3.0 — fold: hero → trust → estado → acciones → stories → oferta.
 * Las novedades van temprano (si hay datos) para híbrido social.
 */
export const ORDEN_RETAIL: TipoModulo[] = [
  'hero',
  'metricas',
  'estado',
  'acciones',
  'novedades',
  'catalogo',
  'ia',
  'promocion',
  'categorias',
  'resenas',
  'ubicacion',
  'horario',
  'pago',
  'canales',
  'galeria',
  'nosotros',
  'faq',
];

const ORDEN_POR_ARQUETIPO: Record<Arquetipo, TipoModulo[]> = {
  retail: ORDEN_RETAIL,
  cita: [
    'hero',
    'metricas',
    'estado',
    'acciones',
    'novedades',
    'servicios',
    'galeria',
    'resenas',
    'equipo',
    'horario',
    'ubicacion',
    'promocion',
    'canales',
    'faq',
  ],
  comida: [
    'hero',
    'metricas',
    'estado',
    'acciones',
    'novedades',
    'catalogo',
    'categorias',
    'ia',
    'promocion',
    'resenas',
    'ubicacion',
    'horario',
    'pago',
    'canales',
  ],
  profesional: [
    'hero',
    'metricas',
    'acciones',
    'nosotros',
    'servicios',
    'certificaciones',
    'resenas',
    'equipo',
    'publicaciones',
    'documentos',
    'faq',
    'ubicacion',
    'horario',
    'canales',
  ],
  alto_ticket: [
    'hero',
    'metricas',
    'acciones',
    'nosotros',
    'catalogo',
    'servicios',
    'resenas',
    'publicaciones',
    'certificaciones',
    'documentos',
    'equipo',
    'ubicacion',
    'canales',
  ],
  local: [
    'hero',
    'metricas',
    'estado',
    'ubicacion',
    'acciones',
    'promocion',
    'horario',
    'pago',
    'canales',
  ],
};

export function ordenArquetipo(arquetipo: Arquetipo): TipoModulo[] {
  return ORDEN_POR_ARQUETIPO[arquetipo] ?? ORDEN_RETAIL;
}
